# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MAD.lair
tagline:          'Games, math, and epic stuff'
description:      'Experiments and thoughts'
url:              https://themaddi3.github.io
baseurl:          /

excerpt_separator: "<!--more-->"

author:
  name:           'Davide C. Milano'
  url:            https://www.instagram.com/dm_maddi3/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
