# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  header_offset:  1

# Permalinks
permalink:        pretty

# Setup
title:            MAD.lair
tagline:          'Games, math, and epic stuff'
description:      'Experiments and thoughts'
lang:             en
timezone:         Europe/Rome
url:              https://madlair.com
baseurl:          ""

excerpt_separator: "<!--more-->"

author:
  name:           'Davide C. Milano'
  url:            https://www.instagram.com/dm_maddi3/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/TheMaDdi3/themaddi3.github.io
